project:
  type: website

website:
  navbar:
    left:
      - text: 大花法蘭西斯
        href: index.qmd
      - text: AI與Python
        href: programming.qmd
      - text: 學術技能
        href: skill.qmd  
      - text: 個體經濟
        href: micro.qmd
      - text: R與Data Science
        href: method.qmd
      - text: 選舉研究
        href: voting.qmd
      - text: 股市分析
        href: stock.qmd
      - text: 生活隨筆
        href: life.qmd
      - text: About
        href: about.qmd
format:
  html:
    theme: flatly
    highlight: pygments
    css: styles.css
    toc: true



